# Generated by Django 2.2 on 2019-05-06 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.ImageField(upload_to='founders')),
                ('name', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.ImageField(upload_to='investors')),
                ('name', models.CharField(max_length=30)),
                ('investment', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('domain', models.CharField(max_length=20)),
                ('networth', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=15)),
                ('site', models.URLField()),
                ('slug', models.SlugField(allow_unicode=True, default='x', unique=True)),
                ('co_founders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Founder')),
                ('investors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Investor')),
            ],
        ),
    ]
