# Generated by Django 2.2 on 2019-05-07 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='co_founders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.Founder'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='investors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.Investor'),
        ),
    ]
