# Generated by Django 2.2 on 2019-05-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190507_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('github', models.URLField(max_length=50)),
                ('resume', models.ImageField(upload_to='resumes')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
