# Generated by Django 2.2 on 2019-05-07 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='co_founders',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='investors',
        ),
        migrations.AddField(
            model_name='application',
            name='startup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app1.Startup'),
        ),
        migrations.AddField(
            model_name='founder',
            name='startup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app1.Startup'),
        ),
        migrations.AddField(
            model_name='investor',
            name='startup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app1.Startup'),
        ),
    ]
