# Generated by Django 2.2 on 2019-05-08 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20190507_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='application',
            name='startup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications', to='app1.Startup'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='startup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='founders', to='app1.Startup'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='startup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='investors', to='app1.Startup'),
        ),
    ]
