# Generated by Django 2.2 on 2019-05-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20190508_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startup',
            options={'ordering': ['name']},
        ),
    ]
